import Navbar from '@components/Layout/Navbar';
import { inter } from '@fonts';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <body className={`w-full h-full ${inter.className}`}>
        <Navbar />
        <Suspense>
          {children}
        </Suspense>
      </body>
    </html>
  )
}

export default RootLayout;